# Generated by Django 5.0.4 on 2024-05-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cigarette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('type_description', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('strength', models.CharField(max_length=50)),
                ('flavor', models.CharField(max_length=50)),
                ('nicotine_content', models.CharField(max_length=50)),
                ('thickness', models.CharField(max_length=50)),
                ('resin_content', models.CharField(max_length=50)),
                ('filter_presence', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DisposableVape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('number_pulls', models.IntegerField()),
                ('number', models.IntegerField()),
                ('strength', models.CharField(max_length=50)),
                ('nicotine_content', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Heating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('holder_charge', models.CharField(max_length=50)),
                ('battery_charge', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('session_time', models.CharField(max_length=50)),
                ('package', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hookah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('height', models.CharField(max_length=50)),
                ('width', models.CharField(max_length=50)),
                ('hose_length', models.CharField(max_length=50)),
                ('bulb_volume', models.CharField(max_length=50)),
                ('material_flask', models.CharField(max_length=50)),
                ('material_bowl', models.CharField(max_length=50)),
                ('material_shaft', models.CharField(max_length=50)),
                ('material_tube', models.CharField(max_length=50)),
                ('connection_type', models.CharField(max_length=50)),
                ('shaft_diameter', models.CharField(max_length=50)),
                ('color_shaft', models.CharField(max_length=50)),
                ('color_bowl', models.CharField(max_length=50)),
                ('tubes_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacity_liquid', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('atomizer', models.CharField(max_length=50)),
                ('vape_refuel', models.CharField(max_length=50)),
                ('power', models.CharField(max_length=50)),
                ('capacity_battery', models.CharField(max_length=50)),
                ('type_battery', models.CharField(max_length=50)),
                ('type_charge', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
